### ISSUE TITLE
Issue with Streaming g code file

### ISSUE THREAD

**Issue by Kruze17** [winder/Universal-G-Code-Sender#1066]
## Problem description 

I am very new to this...
when i click the send button these commands appear in command table...
I mean why are the commands skipped? 
The whole g code file is skipped.. and the elapsed time keeps on increasing forever...
#### Version
  UGS Classic 1.0.9
#### Operating system
  Windows 7 Ultimate
#### Platform
  GRBL 0.9j
#### Other
![ugs](https://user-images.githubusercontent.com/40540237/41819343-6e07fa24-77dc-11e8-9708-4fcb91b86f86.JPG)

**Comment by winder** [comment]
Those 2 commands at the top were skipped because they only contain comments, newer versions of UGS give more information about why commands are skipped.

The pen-down command doesn't have a command letter before the 0 so GRBL detected the error.

The timer not stopping should be fixed in newer versions of UGS.
