### ISSUE TITLE
Feed/Spindle speed override shortcuts do not function when code is being sent

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#1165]
#### Version
  UGS Platform 2.0 - Nightly Build 

#### Operating system
  Windows 7

#### Platform
  GRBL 1.1f

**Comment by carneeki** [comment]
The expectation is that overrides should be sent realtime, that is, they should "jump to the head of the queue" with UGS' internal buffer and be streamed to the controller (eg GRBL) immediately. (if UGS is in the middle of sending a command, it should complete that command and then send the feed override, otherwise strange things may happen).

According to the GRBL manual ([do a find for "Feed overrides:"](https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands)), GRBL prioritises realtime commands (like feed+speed override) and processes them instantly. This makes sense to do it this way for things like feed hold, but also for feed + speed overrides, here's a use case as to why:

Pretend we start at X0 Y0 and run `G1 X400 F100`
and we encounter some chatter, and we want to increase feed rate to overcome the harmonic. Sending a feed override increase of 1% (ie UGS would send a `0x93` byte to increase the feed rate by 1%) and GRBL will start to run the stepper 1% faster (now 101mm / minute).

For GRBL, this should be true for *all* real-time commands, including the necessary ones @AbySet mentions. I think the same would be true of TinyG and Smoothie as well. I was looking at some of the button code last week, and I saw that UGS has some buttons which should send a command immediately using `IController.sendOverrideCommand(Overrides)` (by way of `GUIBackend.sendOverrideCommand(Overrides)`).

@jahnj0584 - do you see anything in the command line to show if UGS attempted to send an override? If not, it could be in here that the problem is occurring (the `if(realTime...` line here near line 774 of `GrblController.java`):
```java
    public void sendOverrideCommand(Overrides command) throws Exception {
        Byte realTimeCommand = GrblUtils.getOverrideForEnum(command, capabilities);
        if (realTimeCommand != null) {
            this.dispatchConsoleMessage(MessageType.INFO, String.format(">>> 0x%02x\n", realTimeCommand));
            this.comm.sendByteImmediately(realTimeCommand);
        }
    }
```

**Comment by jahnj0584** [comment]
I wonder if this is actually just a UGS issue. The built in button for over rides work. If you use a keyboard shortcut, it won't.

**Comment by dgjohnson** [comment]
I confirmed the behavior that the spindle and feed override hotkeys do NOT work when gcode is being sent.
is there any workaround for this?

**Comment by breiler** [comment]
I think that I found the cause so I added a bug label. The service handling shortcuts checks if the machine is idle. Otherwise the command is not sent.
https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/RunActionService.java#L50

**Comment by dgjohnson** [comment]
that may be to systemic to be correct, as other hotkeys work when the machine is not idle...

**Comment by dgjohnson** [comment]
will buy beer for new build with fix! :)

**Comment by dgjohnson** [comment]
> I think that I found the cause so I added a bug label. The service handling shortcuts checks if the machine is idle. Otherwise the command is not sent.
> https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/RunActionService.java#L50

by the way, where is this called when processing the hotkeys?

**Comment by breiler** [comment]
The actions get registered here:
https://github.com/winder/Universal-G-Code-Sender/blob/master/ugs-platform/ugs-platform-ugscore/src/main/java/com/willwinder/ugs/nbp/core/control/RunActionService.java#L82

**Comment by dgjohnson** [comment]
thanks, i'm new to NetBeans, I'm going to compile locally and test the change.

**Comment by breiler** [comment]
> good catch, will buy beer for a pull request! :)

Looking forward to my beer @dgjohnson :)

**Comment by dgjohnson** [comment]
> > good catch, will buy beer for a pull request! :)
> 
> Looking forward to my beer @dgjohnson :)

no problem! tell me where to send it... david@diy.engineering

**Comment by breiler** [comment]
Ha ha, I was only kidding. Just pay it forward!

**Comment by dgjohnson** [comment]
![image](https://user-images.githubusercontent.com/5815517/56048989-8dbabd00-5d16-11e9-898f-18a537d8dfdf.png)
