### ISSUE TITLE
Tiler not working

### ISSUE THREAD

**Issue by jappiemike** [winder/Universal-G-Code-Sender#1271]
I have tried all the most recent versions of UGS and cannot get the tiler to work, it always comes up with rapids lines to where the objects should be but no object, It also shows the program running as the dowel_program and a long line of numbers. There is no tiler program in the folder, I'm using a mac running 10.13.6 with java 8 something.

**Comment by breiler** [comment]
It works for me, do you mind sharing your gcode program that we can try?

![Tiler 2019-10-26 07_29_12](https://user-images.githubusercontent.com/8962024/67614746-7af36b80-f7c2-11e9-9c6c-aac94b7ef14d.gif)

The filename dowel_program is just a generated for the temporary file. It should of course be something like tiler_program so that's an improvement that can be made.

**Comment by jappiemike** [comment]
Hi and thanks for taking the time to help. I just used this file which is the cutout of some perspex circles and was generated by carbide create..


and this is the output after the tiler

it shows the path between the shapes but no code for the actual circles. I’ve tried many of the older versions of UGS but haven’t found one that works.
Cheers
Mike

**Comment by breiler** [comment]
It seems that it has problems parsing some of the comments in the file. As a workaround, remove the lines with parenthesis.

**Comment by jappiemike** [comment]
That worked, I was hoping to just comment out the parenthicated (?) lines but I had to remove them which is a bummer as they have information about the stock size and tool. Thanks for the help.
Cheers
Mike

**Comment by breiler** [comment]
This has been fixed in #1364
