### ISSUE TITLE
Joystick configuration UI issue

### ISSUE THREAD

**Issue by Darren-Smithe** [winder/Universal-G-Code-Sender#1416]
Not a major issue (for me anyway) but may affect people with smaller desktop space or those wanting to configure certain machine actions.

Since fixing the actions cache (thank you Joacim!), the number of machine actions now creates a popup menu too large to fit on a Windows 10 desktop at 1920x1080. Java popups do not seem to automatically implement vertically scrolling popup menus so the menu options may need sub dividing? Maybe a sub menu for Jog XY and Jog Z operations?

UGS Platform 2.0 - Nightly Build Apr 25, 2020
Windows 10
GRBL 1.1f

screenshot shows vertical maximum of my desktop, note some options cannot be selected as they always are clipped from the bottom. I suppose there might be text shrinking operations that could be performed or configured but this is probably contrary to how small screen cnc users would want to operate.

Thanks again for a great cnc tool.

![menu too big](https://user-images.githubusercontent.com/67114628/85861219-e65d6500-b7b7-11ea-87e0-71be8ae3d957.PNG)

**Comment by ronjober** [comment]
i have the same issue with the raspberry pi 4b running the latest version of buster dec 2020,but heres the thing  normaly in order to get the visualizer to work  you have to switch to  fake kms  and move the vco ,but when you move the vco the joy stick tab blues out and no selections available --allso chromium stops working
