### ISSUE TITLE
program not starting properly

### ISSUE THREAD

**Issue by faisalkamalia** [winder/Universal-G-Code-Sender#1517]
Program loads but at welcome screen it stuck and seconds after closes.
![image](https://user-images.githubusercontent.com/22927462/104991605-f59c4c80-5a40-11eb-8994-67ca1da1fa5a.png)
after this screen it not goes to next step.

windows 8.1

**Comment by breiler** [comment]
Could you attach a log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by palestinaikos** [comment]
Not sure if related, but I also can't get it started properly. 
![image](https://user-images.githubusercontent.com/48024024/105616001-e5cf9000-5dd3-11eb-9f2a-2a9424165d25.png)
The log was saved as txt so that github accepts it.
Linux pef7 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
[messages.log.2.txt](https://github.com/winder/Universal-G-Code-Sender/files/5861244/messages.log.2.txt)

I used it without problems on Linux Mint 19 Cinnamon, but after upgrading to v20, I can't get it working again. The same problems arise with stable version as well as with the current nightly build.

Can I provide more info to help with diagnostics? And if so, how? (Sorry, Java is way out of my league :D )

**Comment by breiler** [comment]
@palestinaikos from the log this seems like another problem. It complains about a GL-related problem:
`Caused by: com.jogamp.opengl.GLException: Caught GLException: Profile GL4bc is not available on X11GraphicsDevice``

Does the program `glxgears`work? What kind of graphics card are you using? 

Similar problems have been reported here:
https://github.com/winder/Universal-G-Code-Sender/issues/1391

**Comment by faisalkamalia** [comment]
> Could you attach a log file:
> https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

i attached log file please check sir. thanks

[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/5861745/messages.log)

**Comment by palestinaikos** [comment]
> @palestinaikos from the log this seems like another problem. It complains about a GL-related problem:
> `Caused by: com.jogamp.opengl.GLException: Caught GLException: Profile GL4bc is not available on X11GraphicsDevice``
> 
> Does the program `glxgears`work? What kind of graphics card are you using?

`glxgears` works. `308 frames in 5.0 seconds = 61.441 FPS`


Graphics card: 
`lspci | grep VGA`:
`00:02.0 VGA compatible controller: Intel Corporation HD Graphics 500 (rev 0b)`

I also tried other versions (stable & nightly builds, Linux & All platforms), but only succeeded with running UGS Classic. 

> Similar problems have been reported here:
> #1391

You are correct, my screenshot above looks exactly like <https://github.com/winder/Universal-G-Code-Sender/issues/1391#issuecomment-629631983>. But after following the advice in the #1391 thread, I removed ~/.ugs and ~/.ugsplatform, I managed to replicate the same behaviour as <https://github.com/winder/Universal-G-Code-Sender/issues/1517#issue-788719228> for the nightly build. Stable version seemed to work at first, but soon proved to be glitchy beyond usability.

![Screenshot](https://user-images.githubusercontent.com/48024024/105627750-eea67d00-5e38-11eb-9628-ea6fd6a77aed.png)
When running `sudo ./ugsplatform`, the dark theme is no longer used, but behaviour doesen't change much.

![Screenshot](https://user-images.githubusercontent.com/48024024/105627938-12b68e00-5e3a-11eb-81c3-a986a4a3deb5.png)

Latest log: [messages.log.2.txt](https://github.com/winder/Universal-G-Code-Sender/files/5862020/messages.log.2.txt)

**Comment by breiler** [comment]
The log file is full of GL-specific errors, it seems to be resolved with the 2.4.0-release of Jogamp which is not available yet:
http://forum.jogamp.org/Crash-after-latest-mesa-driver-update-from-ppa-oibaf-td4040300.html

**Comment by sproutecks2125** [comment]
Wanted to post a comment about this not working on Windows 10 as well. I can't seem to even find the log file as indicated in the docs (i.e. no "ugsplatform") file in C:\..\AppData\

I tried to read through some of the links provided in here by other but did not get to a solution. 
Screenshot attached showing "jogamp_exe..." file and where it is hanging the program.

Look forward to a fix as I am really excited to try your software with my xcarve.

Thank you for your work on this project.
![error_ugs](https://user-images.githubusercontent.com/31379397/106379404-59901080-6371-11eb-93d8-e58f7695b3ba.PNG)

**Comment by faisalkamalia** [comment]
> > Could you attach a log file:
> > https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files
> 
> i attached log file please check sir. thanks
> 
> [messages.log](https://github.com/winder/Universal-G-Code-Sender/files/5861745/messages.log)

**Comment by breiler** [comment]
@faisalkamalia did you solve this, and if so how?

**Comment by faisalkamalia** [comment]
no I did not solved this, mine problem is that please check the above comment contains log file.

**Comment by breiler** [comment]
@faisalkamalia Your log file didn't give any clues. Do you have an Antivirus program that might block things?

**Comment by faisalkamalia** [comment]
no i did not have a antivirus. leave it. thanks i will do it my self.
