### ISSUE TITLE
Joystick Gamepad not working Raspberry Pi

### ISSUE THREAD

**Issue by mcinquino** [winder/Universal-G-Code-Sender#1686]
**Describe the bug**
Wired Joystick Gamepad is not recognized 

Link to the joystick: 
https://www.amazon.com/gp/product/B01GR9ZZTS/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

**Expected behavior**
This is my first attempt at using a gamepad so I am not exactly sure what to expect. When plugged in I get no response when attempting to Jog the machine. If I go into options I don't see it listed in joystick tab. (I have not found a screen shot of what this tab should look like when a successful devices is connected and detected to compare my screen to, I am assuming because nothing is shown that it is not seen by UGS?)

I have run a linux command line application that shows linux sees the input from the joystick. 
I checked to make sure the joystick plugin is selected and loaded in UGS. 

The joystick looks "generic" to me but I am thinking that it may not be in the SDL_GameControllerDB and thus not being recognized?

**Version**
UGS Platform 2.0.8, Raspberry Pi

**Hardware**
GRBL 1.1f

**Operating system (please complete the following information):**
Raspbian OS 

**Additional context**
https://www.amazon.com/gp/product/B01GR9ZZTS/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

**Comment by breiler** [comment]
Could not find the controller in the list, you could try out the latest 2.0.13 version which has an updated list.

Otherwise you need to figure out its ID using a mapping tool found here:
https://github.com/gabomdq/SDL_GameControllerDB#mapping-tools

I am closing this issue as its very old and probably not relevant anymore, but feel free to open once you have a device id.
