### ISSUE TITLE
DRO: automatically select text

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1826]
In the DRO, when you right-click an axis value, a popup appears. It would be great if the existing text was selected automatically. This way you could just type a new value directly, instead of the current way where you need to first highlight the text with the cursor.

**Comment by breiler** [comment]
Thanks for the feedback.

It was originally like this but had to be replaced with a popup because the text input fields could not be styled in a good way that was consistent across different OS:es.

There might be another solution where we could temporarily replace the JLabel with a JTextField when it is clicked. But this change will go far down on my priority list though.

**Comment by daxliniere** [comment]
Hey Joacim! Thanks for taking the time to reply.

Ahh, I see what you mean, but I think we're talking about _slightly_ different things. Though it might be more 'slick' to edit the DRO display directly, I don't have any problem with the popup text box.
And to that end, I was thinking you might be able to add a function that simply selects all of the editable text in that box upon popup. Essentially, just add a CTRL+A macro as soon as that dialogbox, then we can type right over it.

**Comment by breiler** [comment]
🤦 Sorry

Great feedback, should be a quick fix!

**Comment by daxliniere** [comment]
haha, all good, man! Thank you for developing this software and let me know if I can help in some way. :)

**Comment by breiler** [comment]
The build server is currently having problems with some tests, but once its up and running again this should be available in the nightly build.

**Comment by daxliniere** [comment]
Oh man, this is really fantastic. I know it's a tiny little thing, but it's a big workflow improvement!
