### ISSUE TITLE
motor is not moving using Arduino and Universal Gcode Sender

### ISSUE THREAD

**Issue by tomsolub** [winder/Universal-G-Code-Sender#209]
Hi,
My name is Lubos and I'm working on my diploma. I have a mechanical loading device, which consists of 3 (maybe 5) stepper motors and I have also three stepper motor drivers and I'd like to control them using Arduino Mega ADK and gcodes. That's why i downloaded Universal Gcode Sender and also Xloader and grbl to enable Arduino to understand gcodes. I wanted to try move one motor, so i wired it to motor driver but when I put some command in Universal Gcode sender using also grbl and Arduino, motor is not moving. But when I connect motor only to Arduino using motor driver and just try some command from Arduino software, motor works. What am I doing wrong? could you please help me? May there be a problem, that I don't have connected all 3 motors to it or it should work no matter how many motors are connected?

Thank you for any kind of help

Best regards,

Lubos

**Comment by tomsolub** [comment]
Hi, I'm sorry to bother you again, feel like an idiot. I used that putty and when I opened the port, there was a command window but nothing worked, nothing happened. I hit the enter there was a blink on Arduino, but motor didn't move. for me even putty is a novelty, maybe I can't work with it, what should I put there actually?....And when I opened the port with UGS and wrote a command, it tells me that it was sent but not done....

Lubos

**Comment by kanere23** [comment]
apparently it is an problem that many user same as me also encountered,
the chipset (Atmega2560 for me) has some hard time understanding of the gcode commands.
it is due to the software, it is built around a arduino uno.
and arduino mega doesn't respont after connect most of the time for users
with the arduino ethernet that i have laying around worked just one of the axis.

This is Version 1.1 (115200 baudrate Programmed on Arduino Mega 2560)
![knipsel2](https://cloud.githubusercontent.com/assets/25063515/21862066/f23c6cf8-d837-11e6-912f-063fa0e0e948.JPG)
![knipsel3](https://cloud.githubusercontent.com/assets/25063515/21862065/f238b2fc-d837-11e6-8ca7-881bbffc5340.JPG)


Does anyone have an answer to this error (A picture of the error same as tomsolub)
![knipsel](https://cloud.githubusercontent.com/assets/25063515/21861856/08d8f0ea-d837-11e6-95af-ffe4ff2efb80.JPG)

**Comment by winder** [comment]
@kanere23 This is usually due to the arduino serial driver not being installed or selecting the wrong port. But since you are using a Atmega2560, which isn't a standard configuration, I'd suspect there might be a problem with that board or the version of grbl you installed isn't compatible with that board.

**Comment by gerritv** [comment]
I added a configurable wait in GbrblPanel to cover what sounds like this situation. The ATmega2560 takes longer to start up so the GUI has to wait a bit longer.

**Comment by winder** [comment]
UGS doesn't have any sort of connection timeout, a listener thread is always running once you click "connect". If anything comes across the wire after that it will show up in the console. So I think this is probably a problem with the hardware/software on the 2560 - trying multiple control software is always a good first troubleshooting step though.

**Comment by gerritv** [comment]
I wasn't clear. My addition of delay was to wait longer before sending status requests, $G, etc.

**Comment by benwc81** [comment]
I am having a similar issue. I am new to the aurdrino and this is the first time that I have set up the CNC Shield. 

Here is whee I am:
I have flashed GRBL 1.1 and set up the library for aurdrino Uno
I have Universal G code sender 1.0.8
Baud rate for the port and UGS are set to 115200
I am on Windows 10

Symptoms:
When I connect with UGS it says that it is connected but does NOT return the GRBL version and I can't access the settings.

Also, when I connect the motors "bump" for a split second and will not respond to commands. 
 All the tutorials I have looked at this worked without a hitch and I can't find anybody else with this exact problem. I am probably missing something small but important. Ca anybody help?

**Comment by winder** [comment]
@benwc81 you need to upgrade UGS to 2.0 for grbl 1.1 support

**Comment by benwc81** [comment]
Thanks for your email. I switched to my MAC Book last night because I couldn't get UGS 2.0 to open on my PC. I have attached a screen shot. I now can connect but still can't get UGS to respond to commands. I am getting a "Grble is not finished booting" error now. This is what I have tried since I posted. I reflashed GRBL just in case, I loaded a serial driver, I jumped the estop pins. I feel like I got one step closer to getting it to work. Is there anything else I can try? Any help would be much appreciated.

 Ben
--------------------------------------------
On Tue, 1/9/18, Will Winder <notifications@github.com> wrote:

 Subject: Re: [winder/Universal-G-Code-Sender] motor is not moving using Arduino and Universal Gcode Sender (#209)
 To: "winder/Universal-G-Code-Sender" <Universal-G-Code-Sender@noreply.github.com>
 Cc: "benwc81" <biiggglle@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, January 9, 2018, 5:18 AM
 
 @benwc81 you need to
 upgrade UGS to 2.0 for grbl 1.1 support
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by shivmahesh** [comment]
On another GRBL console error message after ###connected to COM 1 @115200 baud####                 While starting file stream: GRBL has not finished booting.pls help.

**Comment by winder** [comment]
@shivmahesh this is a fairly generic error message, here is a list of common causes: http://winder.github.io/ugs_website/guide/troubleshooting/#grbl-has-not-finished-booting

**Comment by shivmahesh** [comment]
A)Now on running gcode file on processing 3.0.2 error message err:
unsupported statement.                     G4. P150. ( Wait 150ms).Sir pls
help.what this means.                         B) on running file on ugcs
error message:can not load file. Streaming is still going.
       This message comes when  I click on send file sign.and on Arduino
board rt Rx led continuously blinking ,Evan before click on send small
window.I am totally new be in software related problem.

**Comment by evadsomucad21** [comment]
can anyone help me same issue here i already tried the diff baud rate nothing happen using for a mini laser engrave for the first time

**Comment by BrendonWright** [comment]
I have a bobscnc and have set it up according to the manual. MY MACHINE WILL NOT MOVE :( i have been working on this for days and cant figure it out. I have UGS 2.0 nightly latest version. GRBL 1.1 its flashed to the arduino card. When i connect to UGS. it Connects shows the alarms status, I hit HOME and its goes green HOME but the machine doesn't move...   after a few seconds it goes back to alarm and shows an ALARM9

**Comment by BrendonWright** [comment]
[Error] An error was detected while sending '$H': (ALARM:9) Homing fail. Could not find limit switch within search distances. Try increasing max travel, decreasing pull-off distance, or check wiring. Streaming has been paused.
[Error] Error while processing response <ok>: An unexpected command was completed by the controller.
Grbl 1.1g ['$' for help]
>>> $$
$0 = 5    (Step pulse time, microseconds)
$1 = 25    (Step idle delay, milliseconds)
$2 = 0    (Step pulse invert, mask)
$3 = 0    (Step direction invert, mask)
$4 = 0    (Invert step enable pin, boolean)
$5 = 1    (Invert limit pins, boolean)
$6 = 0    (Invert probe pin, boolean)
$10 = 1    (Status report options, mask)
$11 = 0.010    (Junction deviation, millimeters)
$12 = 0.002    (Arc tolerance, millimeters)
$13 = 1    (Report in inches, boolean)
$20 = 1    (Soft limits enable, boolean)
$21 = 0    (Hard limits enable, boolean)
$22 = 1    (Homing cycle enable, boolean)
$23 = 3    (Homing direction invert, mask)
$24 = 500.000    (Homing locate feed rate, mm/min)
$25 = 8000.000    (Homing search seek rate, mm/min)
$26 = 250    (Homing switch debounce delay, milliseconds)
$27 = 5.000    (Homing switch pull-off distance, millimeters)
$30 = 1000    (Maximum spindle speed, RPM)
$31 = 0    (Minimum spindle speed, RPM)
$32 = 0    (Laser-mode enable, boolean)
$100 = 80.000    (X-axis travel resolution, step/mm)
$101 = 80.000    (Y-axis travel resolution, step/mm)
$102 = 2267.717    (Z-axis travel resolution, step/mm)
$110 = 10000.000    (X-axis maximum rate, mm/min)
$111 = 10000.000    (Y-axis maximum rate, mm/min)
$112 = 500.000    (Z-axis maximum rate, mm/min)
$120 = 800.000    (X-axis acceleration, mm/sec^2)
$121 = 800.000    (Y-axis acceleration, mm/sec^2)
$122 = 300.000    (Z-axis acceleration, mm/sec^2)
$130 = 610.000    (X-axis maximum travel, millimeters)
$131 = 610.000    (Y-axis maximum travel, millimeters)
$132 = 85.000    (Z-axis maximum travel, millimeters)
ok
>>> $G
[GC:G0 G54 G17 G21 G90 G94 M5 M9 T0 F0.0]
ok

**Comment by breiler** [comment]
@BrendonWright could you create a new issue?

**Comment by BrendonWright** [comment]
I did its here https://github.com/gnea/grbl/issues/773 waiting for a comment
