### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by Majestad278** [winder/Universal-G-Code-Sender#213]
I would like to know how to translate into my language program. provided that the author me permission to change the language.

I think the opening to foreign languages is a great opportunity for this type of program.

**Comment by winder** [comment]
All you need to do is add a file to the resources directory with your country code at the end and put in the translations. If you want to download MessagesBundle.properties and send me the translated file I'm happy to integrate it, otherwise just send a pull request!

https://github.com/winder/Universal-G-Code-Sender/tree/master/src/resources

**Comment by Majestad278** [comment]
thanks. I work so hard to send this file.

**Comment by Majestad278** [comment]
how i can test the traduction?

**Comment by lazyzero** [comment]
You can add the new traslation by adding a line in the class AvailableLanguages
https://github.com/winder/Universal-G-Code-Sender/blob/master/src/com/willwinder/universalgcodesender/i18n/AvailableLanguages.java
When you now run UGS you can select your translation from the settings menu.

**Comment by Majestad278** [comment]
thanks
