### ISSUE TITLE
Machine motion leave machine in incremental mode

### ISSUE THREAD

**Issue by woodworkerbob** [winder/Universal-G-Code-Sender#275]
When jogging the machine in the machine control panel, the GRBL status is left in incremental mode via the G91 command.  I suggest the machine be returned to the mode it was in prior to the jog command.  My machine is just about always in absolute mode.

Currently:
G91 X 1

Suggestion:
G91 X 1 G90

**Comment by winder** [comment]
The problem with this is that the machine might not be in absolute mode to begin with, I'm not sure if UGS gets that information currently. I also try to minimize the number of G91/G90 commands being sent since people generally click the jog buttons many times, I'm not sure how important that is for GRBL.
