### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Willson13** [winder/Universal-G-Code-Sender#341]
I have installed the latest Java update, as well as downloaded and unzipped the .zip file for version 1.0.7 & 1.0.9 and I cannot seem to get the window to open. File explorer does not know what app or program to use to open the .jar file. What do I do to fix this issue?

**Comment by winder** [comment]
What operating system are you using?

**Comment by Willson13** [comment]
I'm running windows 10. Is that going to be a problem?

**Comment by winder** [comment]
Not a problem at all. Your question was how to get the file explorer to associate the .jar with Java which is different for every operating system.

This is a little unusual, because the java installer usually does that for you on Windows. It looks like you can find instructions to update file associations here: http://windows.microsoft.com/en-us/windows/change-default-programs#1TC=windows-7

You could also double click the `start-windows.bat` file.
