### ISSUE TITLE
Hotkeys - classic vs platform

### ISSUE THREAD

**Issue by philreindl** [winder/Universal-G-Code-Sender#397]
@winder 
Hotkeys management is one of the next things I'd like to tackle.  100% agree that the hotkeys between the two builds should coexist and ideally share mappings.

At a high level, I think that the GUI backend should be in charge of the keyboard events.  First order of business is to deal with the fact that the command window and file browser will not prevent jogging if arrow keys are pressed.  The way I was thinking of handling that is to have the backend expose a new "grabKeyboardFocus" method which will be fired by UI controls that use the keyboard when they gain focus.  So the browse window, command text field, macro edit fields, etc would all fire that method when they gain focus.  There would also need to be a "releaseKeyboardFocus" method for when focus is lost.

The other main change would be for every button/widget to register themselves with the backend api.  They would give an identification string (probably can use the local id) and a callback function.  We would then define a keymap to tie keyboard buttons to the id strings, which would then fire the appropriate callback when the keyboard button is pressed.  

Does that more or less jibe with what you've got in mind for the platform UI?

**Comment by winder** [comment]
By having hotkeys coexist I was really thinking that we need to make sure hotkeys in the swing GUI don't leak into the platform and vice versa. I think hotkeys should be handled separately. The idea for the BackendAPI was that things the GUI would want to do are exposed to be controlled by whatever presentation layer facilities exist would be used for controlling the interface.

The approach you described still makes sense, but it would be in a class that gets hooked up to the the main window keyboard listener. Since the Netbeans Platform provides its own shortcut manager it would be hard to have it share settings.

Making it easy to call into the backend programmatically was an issue I came across as well. Ideally you want a hotkey/id like you described which doesn't exist in the way I made the original interface. (the same is true for the Settings object). I took a stab at making that work a little better with `public void performAction(ACTIONS action)`

To deal with the keyboard focus, I opted to make the hotkeys a little more deliberate. So instead of 'ARROW', it would use something like 'COMMAND-ARROW' for the default.
