### ISSUE TITLE
Current feed override setting

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#453]
As it stands, using the feed over ride in the option is a crap shoot. Sometimes it works, sometimes it doesnt and you never know when it will be activated. It'd be great if there was something as easy as "sending at: XXX%" underthe file browser or even in the send progress box.

Cheers

**Comment by winder** [comment]
With the new Gcode Processor's there's a disconnect between some options in the "Sender Settings" and "Gcode Processor Settings". Currently some options must be ENABLED in the "Gcode Processor Settings" but configured in the "Sender Settings".

I think I can improve those settings.

**Comment by winder** [comment]
Having a way to see exactly how the gcode is being modified regardless of how it is configured is a great idea.

**Comment by winder** [comment]
I reworked the settings page. All the settings which effect the gcode are now in the `Gcode Processor Configuration` page. After changing a setting it should reload the gcode file so that any settings will be taken into account right away.

Let me know if the override settings still feel like a crap shoot.

**Comment by jahnj0584** [comment]
I'll test it tomorrow!
