### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by cmsteinBR** [winder/Universal-G-Code-Sender#469]
Please, see the figures.

Thanks
![capturar3](https://cloud.githubusercontent.com/assets/21204259/18030791/655b93b0-6c9c-11e6-8989-f14eca0e0bbc.PNG)
![capturar2](https://cloud.githubusercontent.com/assets/21204259/18030792/655e0410-6c9c-11e6-8e3b-3b5422f1cec0.PNG)

**Comment by ml-hn** [comment]
I'm from Germany and I using Windows 10. The GUI shows no special characters (Umlauts). These are all displayed as squares.

Thank You

**Comment by winder** [comment]
@cmsteinBR Thanks, updated these fields. There is a new one for `Pendant` that you can add on POEditor.

@ml-hn Sounds like the same issue as #315

**Comment by cmsteinBR** [comment]
Other translation missing: caption of edit buttons in GCode Processor

**Comment by breiler** [comment]
This has been resolved

**Comment by einencool** [comment]
Hello,
I would like to ask if there is any possibility that I have to install a extra software, so that the german translation will be displayed correctly? I have the Problem, that many "umlauts" are displayed as a black square, and I don't know, what I can do in this case?

![UGS 1](https://user-images.githubusercontent.com/37541729/77225896-ec69f700-6b73-11ea-8c8f-8a7f9214ca1b.PNG)

I've read about the translation and took a look  at the "poeditor" Page, and there are all translations displayed "correctly" like "Fräser Durchmesser" for "Endmill Diameter"

![UGS 2](https://user-images.githubusercontent.com/37541729/77225970-8cc01b80-6b74-11ea-954c-922e3ec5d996.PNG)

Maybe I'm missing something :-)

Greets
Chris
