### ISSUE TITLE
G4 P0.01 Problem

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#494]
I have an issue i can't solve...2 Programs attached:
Prog1....Displays correctly for the first part then all I can see is the Rapids..this file contains a G4 P0.01
Prog2....displays correctly...this file does not contain the G4 code.
both files cut correctly.

I have tried various values for G4 P___ but no luck.
I have run other code with G4 P successfully, but they had only a few instances.

Can a few of You run both codes thru UGS Visualizer and come back with the results please

Window7

Thanks
Doug
[Files.zip](https://github.com/winder/Universal-G-Code-Sender/files/509981/Files.zip)

**Comment by breiler** [comment]
I had problems opening the files due to the line 12 in both files. Had to change the line:
```gcode 
N01 G00 G17 G21 G40 G49 G80 G90 
```
to

```gcode
N01 G17 G21 G40 G49 G80 G90
```

I think the files looks the same in the visualizer:
Prog 1:
![screenshot 2018-07-27 12 56 09](https://user-images.githubusercontent.com/8962024/43317356-ccb6ad2a-919c-11e8-9bd5-df9add01b096.png)

Prog 2:
![screenshot 2018-07-27 12 56 23](https://user-images.githubusercontent.com/8962024/43317365-d434ecf6-919c-11e8-8a5f-997ce317f913.png)

**Comment by breiler** [comment]
Closing due to no feedback from issuer.
