### ISSUE TITLE
Feed override 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#502]
Sonny just said 1.1 will probably be released tonight so was wondering how long we'll have to wait for the feed over ride and current feed rate settings to be released as well. I know he sent out 1.0 early to the devs.

**Comment by chamnit** [comment]
@jahnj0584 : Grbl v1.1 overrides works with UGS platform. There is a menu item you have to enable to view the controls.

**Comment by winder** [comment]
@jahnj0584 They're already in the platform (the prototype has been in since march I think). The interface could probably be tweaked a little, but it's working.

<img width="344" alt="overrides" src="https://cloud.githubusercontent.com/assets/125509/19351937/b5e2e49c-912b-11e6-827d-1f8d28b783bb.png">

**Comment by jahnj0584** [comment]
My panel on windows isn't like that. I have the -- - reset + ++ for each and no numbers alongside
