### ISSUE TITLE
Editor functions question

### ISSUE THREAD

**Issue by DOUG888** [winder/Universal-G-Code-Sender#525]
UGS Platform #676
Just found the Edit functions....Great start...will you be activating the "FIND" function soon as it is currently Greyed out, also as thing progress, "REPLACE ALL" would be a great help.
The rest runs OK so far..

Thanks for the effort
Doug

**Comment by winder** [comment]
The editor is pretty much out the Netbeans editor out of the box. There are a bunch of extension points for things like syntax highlighting, syntax checking, break points, sections (motion groups separated by rapid motions), etc. It's a rabbit hole that I'm not ready to go down yet.

For now I disabled most of the advanced components because enabling them clutter up the top menu with dozens of editor options.

You might not have noticed, but highlighting sections of gcode highlight the corresponding lines in the visualizer.

**Comment by DOUG888** [comment]
Thanks Will...you can close this if you want
