### ISSUE TITLE
G91 Not Working in 2017-02-19 UGS Platform

### ISSUE THREAD

**Issue by rmisko11** [winder/Universal-G-Code-Sender#596]
I can't get relative coordinates (G90) to work;

I have attached the screen capture which should show the movement for a rectangle that ends up at (0,0).  There should be no negative X or Y coordinates.

![2017-03-05_09 48 07_](https://cloud.githubusercontent.com/assets/26075507/23588329/0965720a-018a-11e7-83ca-c22536ea7170.png)

The code shown works as I expect when I send it directly to Laser Engraver.

**Comment by jahnj0584** [comment]
It says in the code that it switches to G91 then back to G90 after its done

**Comment by rmisko11** [comment]
That's true but the code in between should moving the laser according to relative coordinates which it is not

**Comment by winder** [comment]
@rmisko11 Was `G91` in that command remover filter we found the other day? In the visualizer the lines are blocked by the X/Y axis lines, but otherwise looks good to me. It makes a 100mm angle:
<img width="477" alt="screen shot 2017-03-08 at 9 14 35 am" src="https://cloud.githubusercontent.com/assets/125509/23707261/ba84586a-03df-11e7-98d2-323809771619.png">

**Comment by rmisko11** [comment]
Sorry I forgot about this issue.  Yes, it was in the filter and since
removing it G91 works perfectly.
