### ISSUE TITLE
Return to Zero moves Z axis when it shouldn't

### ISSUE THREAD

**Issue by twforeman** [winder/Universal-G-Code-Sender#65]
Just downloaded 1.0.6.

Powered on machine, opened serial connection. All readouts at 0,0,0

Jogged 1mm on the X five times.

Hit "Return to Zero"

Command issued was "G91 G28 X0 Y0 Z4.0"

Why Z4.0?

**Comment by dpeam** [comment]
My issue is simple. I was a CNC machines for about 40 years, I started back when they were incremental machines.
Never, and I mean, never did one drop the Z to just above the work and then rapid the X and Y axis. Or, unlike setup and operators, one likes to repair machines.
I was wondering just who is responsible for this behavior in this sender. It is a very dangerous way to work unless you like crashing your machine.
Always, and I repeat, ALWAYS clear across clamps, vices and other obstacles before moving the X and Y.
So far it seems that most beginner (I am referring to most of the CNC hobbyists) like to drop the Z first.
Comments?

**Comment by aforww** [comment]
dpeam,  I don't know anyone who wants Z to go to zero then  traverse...  That's actually another issue that's open.  When I hit "return to zero"  it issues a G0 Z0 command before the others. No good at all.

**Comment by winder** [comment]
@dpeam I'm responsible for everything in this program. Good and bad. Until starting as a hobbyist 5 years ago my CNC background was zero, so I take feedback from everyone very seriously - especially from professionals like yourself.

The behavior you're commenting on is a bug logged in ticket #542, I think it is related to Machine/Work coordinates (which I don't use, since my machine is not equipped with homing switches). The intended behavior is the Z axis should be raised when left below zero due to a canceled job.

If you notice other behavior that seems unusual please don't hesitate to create a new ticket.

**Comment by dpeam** [comment]
I know it does and that is the problem. It happens in GRBL, Easel and Chillipeper. It is like these people have never actually used a CNC mill before.
What thread is that in, I would very much like to see it.
All it takes is changing a very few lines of code that I do not have access to.

**Comment by aforww** [comment]
@dpeam the issue # is 542. Here's the link.  https://github.com/winder/Universal-G-Code-Sender/issues/542.  Not much in the way of discussion though.

**Comment by dpeam** [comment]
Another issue that is really frustrating. It should send an abort code when cancel is clicked, right now it just keeps on going. There is good reason to cancel or abort and it would except GRBL sends the entire file to the machine instead of line by line. that would make an abort easy.
It pauses with no problem why not abort?

**Comment by winder** [comment]
@dpeam the nightly build will abort the job immediately. The reason why the machine keeps going in older builds is because GRBL needs you to buffer a few commands. So when you cancel no additional commands are sent but the buffered commands keep running.

**Comment by dpeam** [comment]
I am running the latest build pause works nice but cancel does nothing. The only abort is turning off the X-Carve. Just how do I limit the buffer? In command (MDI) it only does each as I tell it to but when running a long file not so much.

**Comment by winder** [comment]
@dpeam what version of GRBL are you using? There is a "single step mode" feature you can enable, but I don't recommend it for anything but troubleshooting.

**Comment by dpeam** [comment]
I just discovered the UGS Platform, what an improvement! One thing though, I was using a Wii controller for a pendant (no continuous jog but I didn’t need the keyboard), the Wii doesn’t seem to connect to the platform as yet, I may be missing something.
So far I really like it and I can use the other UGS to jog in for now.
Haven’t found single step mode either.
Thanks for all your help.
