### ISSUE TITLE
UGS adding vectors when connected to the grbl

### ISSUE THREAD

**Issue by rlwoodjr** [winder/Universal-G-Code-Sender#657]
On a customer's  E3 CNC router. The customer reports.

The screen is adding some lines when UGS is connected. Please compare the pre-connected and the post connected pictures. The lines are not in the g-code in software such as NC Corrector, but do cut when the g-code file is run . (please see the "e" in vector and between the "s" and "t" in test. 

This error does not happen on my E3.

Customer G-code file:
[vector test FULL G W SPACE 1.txt](https://github.com/winder/Universal-G-Code-Sender/files/1002693/vector.test.FULL.G.W.SPACE.1.txt)

![vector 2](https://cloud.githubusercontent.com/assets/10801570/26082870/d1584b8a-3997-11e7-8924-6cd93087345e.PNG)
![vector 1](https://cloud.githubusercontent.com/assets/10801570/26082874/d45d8f7a-3997-11e7-9bba-c8502e5f494f.PNG)

**Comment by winder** [comment]
The commands come from pressing the return to zero button. Seeing that the machine coordinate shows 2.000 and the work coordinates are 0.000, it looks like the user was clearing out some old machine settings. So that's fine.

I can't verify why the program changed, but my guess is that the file was changed and UGS reloaded the file when connecting.
