### ISSUE TITLE
G02/03 arc conversion tool to explicit G01 line segments

### ISSUE THREAD

**Issue by chamnit** [winder/Universal-G-Code-Sender#72]
Grbl can't handle certain arc scenarios, i.e. a user had sequential very short arc commands and it led to a buffer starvation. The arc code in grbl is about as efficient as it's going to get. Seemingly, the only solutions are to increase CPU speed (not possible) or to explicitly break up the G02/03 arcs into line segments. 

This might take some work to integrate into UGS, since you'll have to take some of the output from a g-code parser, keep track of positioning in the program, and then inject G01 statements directly into the stream. Or, create and link a file conversion tool that may be pre-existing (my PreGrbl repo does this, but it's very old).

**Comment by bubalazi** [comment]
I am attempting to make GRBL work with a PPR type machine (two linear and one rotary axes). The end-effector (Its a TIG welder in my case) of the machine follows a "desired/optimal" inclination angle towards the surface being worked on. Main objective is to attempt to hold a relatively constant feedrate on a rectangular path (e.g. 90 degrees, 3mm radius turns). Due to the kinematic configuration of the machine,  simple cartesian paths to followed by the welder are converted to complex curves. To solve the problem I created a simple algorithm to follow these paths, break them up in chunks at the desired max deviation and gave each chunk a execution time in G93 mode. Did some dry testing with motors only (not on machine) and I did work, although with some hickups at the start. I fiddled with the timing and deviations in a couple iterations and I think I got that solved. As a side benefit I got relatively well working feedrate override functionality for my custom setup. Sweet.
