### ISSUE TITLE
Stop and Pause button are greyed out.

### ISSUE THREAD

**Issue by Chromium-x** [winder/Universal-G-Code-Sender#782]
After i start a job the buttons for stop and pause (menu bar) are still grayed out.
The buttons in the drop down menu working properly.

UGS Platform (Version 2.0 [nightly] / Oct 15, 2017)

**Comment by winder** [comment]
What version of GRBL are you using?

**Comment by RoadkillUK** [comment]
I had the same with mine yesterday, couldn't stop or pause also the 'Send Progress' wasn't updating.

grbl 1.1
WinXP
1G mem

however I have a spare grbl board for testing and that does the same on the same PC, but if I use my main PC (not in the same room as the machine) it's fine.

grbl 1.0
Win10
8G mem

**Comment by vMeph** [comment]
Same here stop button dont works
Grbl 1.1

**Comment by jahnj0584** [comment]
I have 1.1 and the latest stable version. The buttons are fine on my end.

On Oct 16, 2017 5:15 PM, "Meph1" <notifications@github.com> wrote:

Same here stop button dont works
Grbl 1.1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/winder/Universal-G-Code-Sender/issues/782#issuecomment-337024668>,
or mute the thread

**Comment by winder** [comment]
Thanks for the reports, for some reason this doesn't happen when I run from my editor, I think it should be resolved now.

**Comment by Chromium-x** [comment]
It works.

Thank's.
