### ISSUE TITLE
Issue Submission Template

### ISSUE THREAD

**Issue by winder** [winder/Universal-G-Code-Sender#865]
GitHub has an "issue template" feature which will pre-populate the description field of new issues.

Things that should be in the issue template:

1. Link to google group in case this is a question and not a bug/feature request.
2. Prompts for version information: UGS (classic/platform/version/date), GRBL, Operating System
3. Link to UGS troubleshooting page: http://winder.github.io/ugs_website/guide/troubleshooting/
4. If you get past all that, list of useful information which help with troubleshooting: Output of `$$`, Gcode file.
5. Prompt for important description elements to create a high quality issue: Expected behavior, actual behavior, steps to reproduce.

Github's issue template documentation: https://help.github.com/articles/creating-an-issue-template-for-your-repository/
Some issue templates: https://github.com/stevemao/github-issue-templates
Projects with good templates: https://github.com/devspace/awesome-github-templates

**Comment by vMeph** [comment]
this is cool is what Marlin uses

`Thank you for submitting your feedback to the Marlin project.
Please use one of the templates below to fill out this box.

------------------------------------------------------------
### Feature Request
Please put [FR] in the issue title: `[FR] Add-on that goes 'ping'`

------------------------------------------------------------
### Compile Error
When I compile with `FEATURE_X` I get an error:
```
Paste_the_error_text_here
```

------------------------------------------------------------
### Bug Report
- Description: ---
- Expected behaviour: ---
- Actual behaviour: ---
- Steps to reproduce:
  - Do this
  - Do that

Attach a ZIP of `Configuration.h` and `Configuration_adv.h` by dropping here.

------------------------------------------------------------
### Bug Report Tips
- When troubleshooting, use `M502` followed by `M500` to reset EEPROM to defaults.
- Use `DEBUG_LEVELING_FEATURE` with `M111 S247` for detailed logging of homing/leveling.
- Format text with: **bold**, _italic_, `code`.
- Format C++ with three backticks, plus "cpp":
```cpp
void my_function(bool do_it) {
  // Hold this spot
}
````
