### ISSUE TITLE
GRBL Odd Parity Bit

### ISSUE THREAD

**Issue by nathanprins** [winder/Universal-G-Code-Sender#873]
Hi, I'm programming a GRBL inspired gcode interpreter on an FPGA for a school project. The problem is that the FPGA requires odd parity which UGS doesn't have. 
Is there a way that I can compile UGS to allow that? 

Thanks in advance!

**Comment by winder** [comment]
There is a communication layer that you could put this in. It wraps the serial library so you can reconfigure it to use whatever settings are needed to support your devices serial protocol.

Specifically I think you need to look at the openCommPortmethod of SerialCommunicator.java

If you have questions let me know, but it's been a long time since I looked at this code so I might not be able to help much.
