### ISSUE TITLE
visualizer sometimes does not act correctly

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#987]
seems like its using an absolute command instead of relative, or vice versa. 

https://www.youtube.com/user/urgamecshk/videos?view_as=subscriber

**Comment by breiler** [comment]
A bug report like this takes a lot of time to decipher so could you please provide more details when creating a issue. Otherwise it would probably take a lot of time for anyone to reproduce it...

I am guessing you are referring to this video:
https://www.youtube.com/watch?v=kVoO0kEfIbg

From the video I can see that the popup menu is old, what version of UGS are you running?
What version of GRBL are you running?
What is the output from `$$` and `$G`

**Comment by jahnj0584** [comment]
1.1 and feb 18. I can't force reproduce it. Occasionally UGS will launch
and do this. This is the third time for me. It also doesn't send me macros
correctly when it is like this.

**Comment by breiler** [comment]
Closing as the video is no longer available
